name: Generate SBOM

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Run Anchore SBOM action
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: .  
          output: sbom-findings.json

      # Upload the SBOM as an artifact
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-findings
          path: sbom-findings.json
