name: OWASP ZAP Security Scan pt.2

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Docker Hub 
        uses: docker/login-action@v3 
        with: 
          username: ${{ secrets.DOCKERHUB_USER }} 
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Pull ZAP Docker Image 
        run: docker pull ghcr.io/zaproxy/zap2docker-stable:latest

      - name: Start ZAP API
        run: |
          docker run -d --name zap -p 8080:8080 owasp/zap2docker-stable

      - name: Generate SBOM
        run: |
          cyclonedx-py --input-file ./requirements.txt --output-file ./bom.json --output-format json

      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: http://localhost:3000
          docker_name: 'owasp/zap2docker-stable'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sbom
          path: ./bom.json

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-report
          path: ./zap-report.json
