name: OWASP ZAP Security Scan pt.2

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Django Application
        run: |
          python manage.py runserver 0.0.0.0:3000 &
        working-directory: .

      - name: Wait for Target Application
        run: |
          for i in {1..10}; do
            if curl --output /dev/null --silent --head --fail http://localhost:3000; then
              echo "Target is ready!"
              break
            fi
            echo "Waiting for target to start..."
            sleep 5
          done

      - name: Start ZAP API
        run: |
          docker run -d --name zap -p 8080:8080 zaproxy/zap-stable

      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: http://localhost:3000
          docker_name: 'zaproxy/zap-stable'
          cmd_options: '-a'

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-report
          path: ./zap-report.json
