name: OWASP ZAP Security Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Run DAST scan on the web application

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GITHUB_USER }}
          password: ${{ secrets.GITHUB_PWD }}


      - name: Run OWASP ZAP scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'owasp/zap2docker'
          target: http://localhost:3000
          cmd_options: '-a'
